### ISSUE TITLE
Why is auth/userkey:generatekey granted to managers by default?

### ISSUE THREAD

**Issue by mudrd8mz** [CatalystIT-AU/moodle-auth_userkey#2]
From my understanding, this capability is supposed to be granted to the user that represents the external app using this auth method. Just wondering what is the use case for granting this to managers (or actually any human users).

**Comment by dmitriim** [comment]
Hi David,

Actually this permission should be granted to a web service user(s) as a keys gets generated by a web service call. So once you create a token for a user, this user has to have this permission to generate keys.

I'll update the plugin documentation.
